using System.Text;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PresetConverter;

[TestClass]
public sealed class PrusaPresetReaderTests
{
    [TestMethod]
    [TestCategory("Prusa")]
    [Description("Preset inheritance is flattened while incomplete presets are skipped")]
    public void Preset_inheritance_is_flattened_while_incomplete_presets_are_skipped()
    {
        // Arrange
        var services = new ServiceCollection();
        services.AddSingleton(typeof(Microsoft.Extensions.Logging.ILogger<>), typeof(NullLogger<>));
        services.AddPrusa(options => options.PresetIdPattern = ".*");
        using var provider = services.BuildServiceProvider();
        var reader = provider.GetRequiredService<IPresetReader>();
        using var stream = new MemoryStream(Encoding.UTF8.GetBytes("""
            # generated by PrusaSlicer 2.9.0

            [print:Broken Print]
            inherits = *missing_parent*
            layer_height = 0.2

            [filament:Parent PLA]
            alias = Parent PLA
            filament_type = PLA
            filament_colour = #FF8000
            filament_diameter = 1.75
            filament_density = 1.24
            filament_cost = 29.99
            temperature = 205
            first_layer_temperature = 215
            nozzle_temperature_range_low = 190
            nozzle_temperature_range_high = 230
            bed_temperature = 55
            first_layer_bed_temperature = 60
            filament_max_volumetric_speed = 0
            min_fan_speed = 35
            max_fan_speed = 100
            fan_below_layer_time = 20
            disable_fan_first_layers = 3
            fan_always_on = 1
            full_fan_speed_layer = 5
            filament_cooling_moves = 4
            filament_cooling_initial_speed = 2.2
            filament_cooling_final_speed = 3.3
            filament_loading_speed = 28
            filament_loading_speed_start = 3
            filament_unloading_speed = 90
            filament_unloading_speed_start = 100
            filament_minimal_purge_on_wipe_tower = 15
            filament_soluble = 1
            filament_multitool_ramming = 1
            filament_multitool_ramming_flow = 10
            filament_multitool_ramming_volume = 20
            filament_ramming_parameters = 120 100 6.6 6.8 7.2
            filament_stamping_distance = 42
            filament_stamping_loading_speed = 33
            filament_toolchange_delay = 1.5
            filament_shrinkage_compensation_xy = 1.25%
            filament_shrinkage_compensation_z = 99.5%

            [filament:Child PLA @0.4 nozzle]
            alias = Child PLA
            inherits = Parent PLA
            filament_max_volumetric_speed = 3
            """));

        // Act
        var presets = reader.ReadPresets(stream, "bundle.ini").ToArray();

        // Assert
        Assert.AreEqual(2, presets.Length);
        var child = (FilamentPreset)presets.Single(preset => preset.Name == "Child PLA");
        Assert.AreEqual(PresetKind.Filament, child.Kind);
        Assert.AreEqual("Child PLA @0.4 nozzle", child.PresetId);
        Assert.AreEqual("PLA", child.MaterialType);
        Assert.AreEqual("#FF8000", child.Color);
        Assert.AreEqual(1.24m, child.Density);
        Assert.AreEqual(29.99m, child.Cost);
        Assert.AreEqual(true, child.IsSoluble);
        Assert.AreEqual(3m, child.MaxVolumetricSpeed);
        Assert.AreEqual(205, child.NozzleTemperature);
        Assert.AreEqual(190, child.NozzleTemperatureRangeLow);
        Assert.AreEqual(230, child.NozzleTemperatureRangeHigh);
        Assert.AreEqual(35m, child.FanMinSpeed);
        Assert.AreEqual(100m, child.FanMaxSpeed);
        Assert.AreEqual(20m, child.FanCoolingLayerTime);
        Assert.AreEqual(3, child.CloseFanFirstLayers);
        Assert.AreEqual(true, child.KeepFanAlwaysOn);
        Assert.AreEqual(5, child.FullFanSpeedLayer);
        Assert.AreEqual(4, child.CoolingMoves);
        Assert.AreEqual(2.2m, child.CoolingInitialSpeed);
        Assert.AreEqual(3.3m, child.CoolingFinalSpeed);
        Assert.AreEqual(1.25m, child.ShrinkageCompensationXY);
        Assert.AreEqual("99.5%", child.ShrinkageCompensationZ);
        Assert.AreEqual(28m, child.LoadingSpeed);
        Assert.AreEqual(3m, child.LoadingSpeedStart);
        Assert.AreEqual(90m, child.UnloadingSpeed);
        Assert.AreEqual(100m, child.UnloadingSpeedStart);
        Assert.AreEqual(15m, child.MinimalPurgeOnWipeTower);
        Assert.AreEqual(true, child.IsMultiToolRammingEnabled);
        Assert.AreEqual(10m, child.MultiToolRammingFlow);
        Assert.AreEqual(20m, child.MultiToolRammingVolume);
        Assert.AreEqual("120 100 6.6 6.8 7.2", child.RammingParameters);
        Assert.AreEqual(42m, child.StampingDistance);
        Assert.AreEqual(33m, child.StampingLoadingSpeed);
        Assert.AreEqual(1.5m, child.ToolChangeDelay);
    }

    [TestMethod]
    [TestCategory("Prusa")]
    [Description("Preset id pattern skips non-matching filament variants")]
    public void Preset_id_pattern_skips_non_matching_filament_variants()
    {
        // Arrange
        var services = new ServiceCollection();
        services.AddSingleton(typeof(Microsoft.Extensions.Logging.ILogger<>), typeof(NullLogger<>));
        services.AddPrusa(options => options.PresetIdPattern = "^[^@]+$");
        using var provider = services.BuildServiceProvider();
        var reader = provider.GetRequiredService<IPresetReader>();
        using var stream = new MemoryStream(Encoding.UTF8.GetBytes("""
            [filament:Shared PLA]
            alias = Shared PLA
            filament_type = PLA
            filament_diameter = 1.75

            [filament:Shared PLA @MK4]
            alias = Shared PLA
            inherits = Shared PLA
            temperature = 215
            """));

        // Act
        var presets = reader.ReadPresets(stream, "bundle.ini").ToArray();

        // Assert
        Assert.AreEqual(1, presets.Length);
        Assert.AreEqual("Shared PLA", presets[0].PresetId);
    }

    [TestMethod]
    [TestCategory("Prusa")]
    [Description("Preset id pattern can select printer specific filament variants")]
    public void Preset_id_pattern_can_select_printer_specific_filament_variants()
    {
        // Arrange
        var services = new ServiceCollection();
        services.AddSingleton(typeof(Microsoft.Extensions.Logging.ILogger<>), typeof(NullLogger<>));
        services.AddPrusa(options => options.PresetIdPattern = ".*@MK4S.*");
        using var provider = services.BuildServiceProvider();
        var reader = provider.GetRequiredService<IPresetReader>();
        using var stream = new MemoryStream(Encoding.UTF8.GetBytes("""
            [filament:Shared PLA]
            alias = Shared PLA
            filament_type = PLA
            filament_diameter = 1.75

            [filament:Shared PLA @MK4S]
            alias = Shared PLA
            inherits = Shared PLA
            temperature = 215

            [filament:Shared PLA @MINI]
            alias = Shared PLA
            inherits = Shared PLA
            temperature = 220
            """));

        // Act
        var presets = reader.ReadPresets(stream, "bundle.ini").ToArray();

        // Assert
        Assert.AreEqual(1, presets.Length);
        Assert.AreEqual("Shared PLA @MK4S", presets[0].PresetId);
    }
}
